from __future__ import annotations

from typing import Annotated, List, TypedDict, Dict, Any

from langgraph.graph.message import add_messages


class ResearchState(TypedDict, total=False):
    """
    Shared state passed between agents in the research workflow.
    """

    # User query driving the research process
    query: str

    # Raw text results from DuckDuckGo (one entry per search call)
    search_results: List[str]

    # Summaries of search results created by the summarizer agent
    summaries: List[str]

    # Feedback from the critic agent about the quality/completeness of summaries
    critique: str

    # Final synthesized research report produced by the synthesizer agent
    final_report: str

    # Revision cycle counter used for conditional routing in the graph
    iteration: int

    # Total wall-clock run time for the research process
    elapsed_seconds: float

    # ISO timestamp for when the run was executed
    timestamp: str

    # Which LLM model produced this output
    model_used: str

    # How many times the critic requested a revision loop
    revision_count: int

    # Sub-queries generated by the planner agent
    sub_queries: List[str]

    # Plan reasoning — why the planner chose these sub-queries
    plan_reasoning: str

    # Which sub-query produced which results (parallel tracking)
    search_results_per_query: List[Dict[str, Any]]

    # Full message history across all agents (managed by LangGraph's add_messages)
    messages: Annotated[list, add_messages]

